import Layout from "Components/Layout/Layout";
import Head from "next/head";
import "styles/globals.scss";
import "styles/utilities/utilities.scss";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>MSSN B-ZONE Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.svg" />
      </Head>
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </>
  );
}

export default MyApp;
